"""Parse and round-trip charts in all four Phimakor formats.

Covers the format-probing API: `detect_format_bytes` / `detect_format` and
`parse_chart_bytes` / `parse_chart` for PEC, PGR, PSS and PMK samples, plus
`RPEChart.to_pss` / `RPEChart.from_pss`, `Chart.hits_before` / `Chart.textures`
and `ChartInfo.from_info_txt`. Every assertion is structural (line/note counts,
BPM list, offset) so the script stays honest across format conventions.

Dependencies: only `phimakor` (built via `python -m maturin build --release`,
then `pip install target/wheels/phimakor-*.whl`). No GUI, no chart directory.

Run:
    python example/format_roundtrip.py
"""

import base64
import json
import os
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import phimakor as pk

# A tiny PMK1 sample, generated by the crate's `pmk::to_bytes` (one line
# "Main", one tap note at beat 4.0, 120 BPM, offset 50 ms). PMK has no Python
# serialization API yet, so the example only exercises the read-only parse
# path against this embedded fixture.
PMK_B64 = (
    "UE1LMU1FVEEjAAAAdmVyc2lvbj0xCm9mZnNldD01MApycGVfY29tcGF0PTE2MApJTkZPLAIAAHsiaWQiO"
    "m51bGwsInVwbG9hZGVyIjpudWxsLCJuYW1lIjoiUE1LIEZpeHR1cmUiLCJkaWZmaWN1bHR5IjoxMi4wLC"
    "JsZXZlbCI6IklOIiwiY2hhcnRlciI6ImZpeHR1cmUiLCJjb21wb3NlciI6ImZpeHR1cmUiLCJpbGx1c3"
    "RyYXRvciI6IlVLIiwiY2hhcnQiOiJjaGFydC5qc29uIiwiZm9ybWF0IjpudWxsLCJtdXNpYyI6InNvbmc"
    "ubXAzIiwiaWxsdXN0cmF0aW9uIjoiYmFja2dyb3VuZC5wbmciLCJ1bmxvY2tWaWRlbyI6bnVsbCwicHJl"
    "dmlld1N0YXJ0IjowLjAsInByZXZpZXdFbmQiOm51bGwsImFzcGVjdFJhdGlvIjoxLjc3Nzc3NzgsImJh"
    "Y2tncm91bmREaW0iOjAuNiwibGluZUxlbmd0aCI6Ni4wLCJvZmZzZXQiOjAuMCwidGlwIjpudWxsLCJ0"
    "YWdzIjpbXSwiaW50cm8iOiIiLCJob2xkUGFydGlhbENvdmVyIjpmYWxzZSwibm90ZVVuaWZvcm1TY2FsZ"
    "SI6ZmFsc2UsImZvcmNlQXNwZWN0UmF0aW8iOmZhbHNlLCJ1c2VScGUxNzBTcGVlZCI6bnVsbCwidXNlQ"
    "XR0YWNrVWlGaXgiOm51bGwsImNyZWF0ZWQiOm51bGwsInVwZGF0ZWQiOm51bGwsImNoYXJ0VXBkYXRlZC"
    "I6bnVsbH1CUE0gEAAAAAAAAAAAAAAAAAAAAAAAXkBMSU5FJQAAAAEAAAD/////AAAAAAAAAAAEAAAACAA"
    "AAE1haW5saW5lLnBuZwBOT1RFNAAAAAAAAAABAAAAAQEAAAAAAAAAABBAAAAAAAAAEECamZk+AAAAAAA"
    "AgD8AAIA//wAAAPAjdElFVk5UQAAAAAAAAAAAAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAACBAAAB/QwA"
    "Af0MAAAAAAACAPwAAAAAAAAAAAAAAAAAAAABFTkQgHAAAAAIAAABOT1RFpAIAAAAAAABFVk5U4AIAAAA"
    "AAAA="
)


def build_rpe_json():
    """A small two-line chart: line 0 with two taps + a hold, line 1 a drag
    line using a custom texture (so `Chart.textures()` has something to find)."""
    return {
        "META": {"offset": 50, "RPEVersion": 160},
        "BPMList": [{"bpm": 120.0, "startTime": [0, 0, 1]}],
        "judgeLineList": [
            {
                "Name": "Main",
                "Texture": "line.png",
                "father": -1,
                "isCover": 0,
                "eventLayers": [{
                    "alphaEvents": [{"start": 255, "end": 255, "startTime": [0, 0, 1],
                                     "endTime": [0, 16, 1], "easingType": 1}],
                    "moveXEvents": [], "moveYEvents": [], "rotateEvents": [], "speedEvents": [],
                }],
                "notes": [
                    {"type": 1, "above": 1, "startTime": [0, 2, 1], "endTime": [0, 2, 1],
                     "positionX": -0.2, "yOffset": 0.0, "alpha": 255, "speed": 1.0},
                    {"type": 3, "above": 1, "startTime": [0, 6, 1], "endTime": [0, 8, 1],
                     "positionX": 0.1, "yOffset": 0.0, "alpha": 255, "speed": 1.0},
                ],
            },
            {
                "Name": "Sky",
                "Texture": "bg.png",
                "father": 0,
                "isCover": 0,
                "eventLayers": [{
                    "alphaEvents": [], "moveXEvents": [], "moveYEvents": [], "rotateEvents": [],
                    "speedEvents": [],
                }],
                "notes": [
                    {"type": 2, "above": 1, "startTime": [0, 4, 1], "endTime": [0, 4, 1],
                     "positionX": 0.5, "yOffset": 0.0, "alpha": 255, "speed": 1.0},
                ],
            },
        ],
    }


def core_stats(rpe):
    """(line_count, note_counts_per_line, bpm_list) — the structure every
    format parser must reproduce. Offset is excluded: each format carries it
    differently (see the per-format offset checks below)."""
    return (
        rpe.judge_line_count(),
        [rpe.judge_line(i).note_count() for i in range(rpe.judge_line_count())],
        rpe.bpm_list(),
    )


def check(tag, cond, detail=""):
    assert cond, f"FAIL [{tag}] {detail}"
    print(f"  ok [{tag}] {detail}")


def main():
    print("== format_roundtrip: PEC / PGR / PSS / PMK parsing + round-trips ==")

    base = pk.RPEChart.from_json(json.dumps(build_rpe_json()))
    base_stats = core_stats(base)
    print(f"reference RPE chart: {base_stats}, offset={base.offset}ms")

    # --- PSS: serialize with to_pss, parse back with parse_chart_bytes and
    # --- from_pss, assert the structure survives the round-trip.
    # NOTE: to_pss() yields a list of ints (PyO3 Vec<u8>), so wrap in bytes().
    pss = bytes(base.to_pss())
    # Known upstream misdetection (chart_format.rs detect order): the PSS meta
    # record contains "format_version", so PgrParser::detect wins before
    # PssParser::detect. Pinned here so a fix is noticed; parsing by explicit
    # format below is unambiguous.
    check("pss detect (pinned)", pk.detect_format_bytes(pss) == "pgr",
          "PSS misdetected as PGR until chart_format.rs detect order is fixed")
    back = pk.parse_chart_bytes("pss", pss)
    check("pss parse_chart_bytes", core_stats(back) == base_stats, str(core_stats(back)))
    direct = pk.RPEChart.from_pss(pss)
    check("pss from_pss", core_stats(direct) == base_stats, str(core_stats(direct)))
    # PSS carries the offset on its meta record (from the ChartInfo handed to
    # to_pss, which defaults to 0) — the chart META offset is not serialized.
    check("pss offset on info record", back.offset == 0,
          f"chart META offset not carried, got {back.offset}ms")
    check("pss to_json stable", pk.RPEChart.from_json(back.to_json()).judge_line_count() == 2)

    # --- PEC: hand-written PhiEdit text chart. First line is the offset in
    # --- ms; `bp` sets BPM (either argument order is accepted).
    pec = (
        "100\n"
        "bp 120 0\n"
        "n1 0 1 0.3 1 0\n"        # tap on line 0 at beat 1
        "n3 0 6 0.1 1 0\n"        # hold on line 0 at beat 6
        "ca 0 4 255\n"            # alpha 255 at beat 4
        "cp 0 2 700 1024\n"       # move to center at beat 2
    ).encode()
    check("pec detect", pk.detect_format_bytes(pec) == "pec", "text chart")
    pec_chart = pk.parse_chart_bytes("pec", pec)
    stats = core_stats(pec_chart)
    check("pec parse", stats[0] == 1 and stats[1] == [2], str(stats))
    check("pec events", len(pec_chart.judge_line(0).events("alpha")) == 1, "alpha keyframe")
    check("pec bpm", [b for b in pec_chart.bpm_list()] == [(120.0, 0.0)], str(pec_chart.bpm_list()))

    # --- PGR: Phigros official JSON (no META). The parser's detect() looks
    # --- for the snake_case keys of the official format, while its serde
    # --- struct expects camelCase — detection and parsing currently disagree
    # --- (upstream chart_format.rs inconsistency), so both paths are
    # --- exercised explicitly on their own samples.
    pgr_detect = json.dumps({
        "format_version": 1,
        "offset": 0.25,
        "judge_line_list": [{"bpm": 150.0, "notes_above": []}],
    }).encode()
    check("pgr detect", pk.detect_format_bytes(pgr_detect) == "pgr",
          "official snake_case keys")
    pgr = json.dumps({
        "formatVersion": 1,
        "offset": 0.25,
        "judgeLineList": [{
            "bpm": 150.0,
            "notesAbove": [
                {"kind": 1, "time": 2.0, "positionX": 0.0, "holdTime": None},
                {"kind": 2, "time": 5.0, "positionX": 0.4, "holdTime": 1.0},
            ],
            "speedEvents": [{"startTime": 0.0, "endTime": 8.0, "value": 1.0}],
        }],
    }).encode()
    pgr_chart = pk.parse_chart_bytes("pgr", pgr)
    stats = core_stats(pgr_chart)
    check("pgr parse", stats[0] == 1 and stats[1] == [2], str(stats))
    check("pgr offset", pgr_chart.offset == 250, f"{pgr_chart.offset} ms")

    # --- PMK: binary Phimakor container (read-only in Python).
    pmk_bytes = base64.b64decode(PMK_B64)
    check("pmk detect", pk.detect_format_bytes(pmk_bytes) == "pmk", f"{len(pmk_bytes)} bytes")
    pmk_chart = pk.parse_chart_bytes("pmk", pmk_bytes)
    stats = core_stats(pmk_chart)
    check("pmk parse", stats[0] == 1 and stats[1] == [1], str(stats))
    pmk_note = pmk_chart.judge_line(0).notes()[0]
    check("pmk note beat", abs(pmk_note.beat - 4.0) < 1e-9, f"beat {pmk_note.beat:.1f}")

    # --- File-based variants: write bytes to a temp dir, probe by path.
    with tempfile.TemporaryDirectory() as tmp:
        for fmt, data, detect_ok in [
            ("pec", pec, "pec"),
            ("pgr", pgr, "unknown"),   # parse sample is camelCase; snake_case detect sample used below
            ("pss", pss, "pgr"),       # PSS misdetected as pgr (pinned above)
            ("pmk", pmk_bytes, "pmk"),
        ]:
            path = os.path.join(tmp, f"sample.{fmt}")
            with open(path, "wb") as f:
                f.write(data)
            if detect_ok:
                check(f"{fmt} detect_format(path)", pk.detect_format(path) == detect_ok)
            via_file = pk.parse_chart(fmt, path)
            check(f"{fmt} parse_chart(path)", via_file.judge_line_count() > 0)
        pgr_path = os.path.join(tmp, "sample_detect.pgr")
        with open(pgr_path, "wb") as f:
            f.write(pgr_detect)
        check("pgr detect_format(path)", pk.detect_format(pgr_path) == "pgr")

    # --- Analysis helpers on the parsed reference chart.
    chart = pk.Chart.from_rpe_chart(base)
    check("hits_before", chart.hits_before(chart.duration() + 1.0) == chart.max_combo(),
          f"{chart.hits_before(0.0)} @t=0, {chart.max_combo()} total")
    textures = chart.textures()
    check("textures", "bg.png" in textures, str(textures))
    check("rpe_version", base.rpe_version == 160, str(base.rpe_version))

    # --- ChartInfo.from_info_txt metadata parsing (RPE export format).
    info = pk.ChartInfo.from_info_txt("Name: Demo\nComposer: phimakor\nCharter: me\nLevel: IN 15\n")
    check("info_txt", info.name == "Demo" and info.composer == "phimakor"
           and info.level == "IN 15", repr(info))

    print("\nformat_roundtrip: all checks passed")


if __name__ == "__main__":
    main()
