[package]
name = "phimakor"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
description = "A Phigros/Phira high performance chart editor/previewer that with any you need it. Including Python, Gui, FXs and More Fancy And Smoothly."

[features]
profiling = ["dhat", "tracy-client"]
python = ["dep:pyo3"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_yaml = "0.9"
winit = "*"
wgpu = "*"
pollster = "*"
rodio = "*"
image = "*"
bytemuck = { version = "*", features = ["derive"] }
fontdue = "*"
softbuffer = "*"
iced = { version = "*", features = ["tiny-skia", "advanced", "image"] }
iced_tiny_skia = "*"
tiny-skia = "*"
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter", "time", "registry"] }
tracing-flame = "*"
zip = { version = "2", default-features = false, features = ["deflate"] }
dhat = { version = "*", optional = true }
tracy-client = { version = "*", optional = true }
pyo3 = { version = "0.22", optional = true, features = ["extension-module"] }


[dev-dependencies]
criterion = "*"

[target.'cfg(loom)'.dependencies]
loom = "0.7"

[[bench]]
name = "extract"
harness = false

[profile.dev]
codegen-units = 256
incremental = true

[profile.release]
lto = "thin"
codegen-units = 16
